name: test_suite

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'bin/*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'bin/*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

        with:
          ruby-version: '3.0'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test